FROM bitnami/spark:3.3.2

COPY TopCuisine-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/TopCuisine-1.0-SNAPSHOT-jar-with-dependencies.jar

COPY CsvUpload-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/CsvUpload-1.0-SNAPSHOT-jar-with-dependencies.jar

