services:
  namenode:
    image: apache/hadoop:3.3.5
    container_name: namenode
    hostname: namenode
    command: [ "hdfs", "namenode" ]
    ports:
      - 9870:9870
      - 9010:9000
    env_file:
      - config.env
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode:
    image: apache/hadoop:3.3.5
    container_name: datanode
    command: [ "hdfs", "datanode" ]
    env_file:
      - config.env
  resourcemanager:
    image: apache/hadoop:3.3.5
    container_name: resourcemanager
    hostname: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - config.env
    volumes:
      - ./test.sh:/opt/test.sh
  nodemanager:
    container_name: nodemanager
    image: apache/hadoop:3.3.5
    command: [ "yarn", "nodemanager" ]
    env_file:
      - config.env

  spark-master:
    image: spark
    container_name: spark-master
    depends_on:
      - namenode
      - datanode
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_MASTER_OPTS=-Dspark.master.rest.enabled=true


  spark-worker-1:
    image: spark
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - JDK_JAVA_OPTIONS=--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

  spark-worker-2:
    image: spark
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      - JDK_JAVA_OPTIONS=--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

  spring-app:
    image: myapp
    container_name: spring-app
    ports:
      - "8889:8888"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
